### ISSUE TITLE
Pytailwindcss doesn't work with Docker

### ISSUE THREAD

**Issue by W1mble** [timonweb/pytailwindcss#7]
Setting pytailwindcss in the requirements.txt file causes error after tailwindcss command is ran from bash inside the container.

Dockerfile:
COPY requirements.txt /tmp/pip-tmp/
RUN pip --disable-pip-version-check install  -r /tmp/pip-tmp/requirements.txt && \
    rm -rf /tmp/pip-tmp

Traceback (most recent call last):
  File "/usr/local/bin/tailwindcss", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/pytailwindcss/__main__.py", line 9, in main
    completed_process = pytailwindcss.run(
  File "/usr/local/lib/python3.10/site-packages/pytailwindcss/__init__.py", line 45, in run
    install(version, bin_path)
  File "/usr/local/lib/python3.10/site-packages/pytailwindcss/__init__.py", line 69, in install
    return install_binary(version, ensure_is_pathlib_path(bin_path))
  File "/usr/local/lib/python3.10/site-packages/pytailwindcss/installation.py", line 25, in install_binary
    os.makedirs(bin_path.parent, exist_ok=True)
  File "/usr/local/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.10/site-packages/pytailwindcss/bin

If you build your container and run pip install pytailwindcss from the bash and run tailwindcss then it works. But not from the requirements.txt

**Comment by mpizosdim** [comment]
Have you found a solution to that?

**Comment by jorgeav527** [comment]
I'm running this with fastAPI and is running totally fine inside the docker container

`FROM tiangolo/uvicorn-gunicorn-fastapi:python3.10

WORKDIR /proj

COPY . .
COPY ./requirements.* .

RUN pip install --no-cache-dir --upgrade -r requirements.dev.txt`

The only problem is that even if i update the the code I have to see how to trigger the updates to the scream

**Comment by timonweb** [comment]
After you run the install command in the Dockerfile, add the following:

```
RUN tailwindcss_install
```

This will install the binary in the container before the code is run.
